# Generated by Django 4.0.4 on 2022-05-20 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category_name',
        ),
    ]
